<?php
/**
 * 自動ログイン用。
 **/
class Bd_Auth_Adapter_DbAutoLogin extends Sdx_Auth_Adapter_Db2
{

  /**
   * Cookieに保存したユニークなトークン
   */
  private $_token;

  /**
   * @param string $token Cookieに保存したユニークなトークン
   */
  public function __construct($token)
  {
    $this->_token = $token;
  }

  /**
   * アカウントのデータを検索して返す
   * @return boolean|mixed
   */
  protected function _find()
  {
    throw new Sdx_Exception('This method is generated by enable-acl script. Please implement this method.');
  }

  /**
   * パスワードが一致しているか検証する
   * @param mixed $account
   * @return bool|array セッションの保持されてSdx_Userから取得可能になります。例：array('login_id'=>'xxxx', 'role'=>'xxx')
   */
  protected function _auth($account)
  {
    throw new Sdx_Exception('This method is generated by enable-acl script. Please implement this method.');
  }
}